"""empty message

Revision ID: c393a9229995
Revises: 
Create Date: 2019-12-28 11:42:07.296985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c393a9229995'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('match_id', sa.VARCHAR(), nullable=True),
    sa.Column('x', sa.INTEGER(), nullable=True),
    sa.Column('y', sa.INTEGER(), nullable=True),
    sa.Column('owner', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('next_player', sa.VARCHAR(), nullable=True),
    sa.Column('winner', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
